### ISSUE TITLE
The latest released package doesn't contain a license

### ISSUE THREAD

**Issue by honzajavorek** [fb55/boolbase#3]
A similar problem to https://github.com/fb55/domelementtype/issues/8. The package is a proprietary code unless published with the full license text. However, projects such as `enzyme` depend on this library.

**Comment by patricksmms** [comment]
@fb55, any chance of getting the license file on the repo and on the npm package?

**Comment by opichals** [comment]
@fb55 This is quite easy to fix.

It would be nice to get the `boolbase@1.0.1` by just doing another `npm version patch && npm publish` so that the license file gets picked by the up-to-date npm version and published along the package contents.

**Comment by fb55** [comment]
The purpose of this module is to provide functions that are the same instance in-between different packages (to maintain referential integrity). Publishing a second version of this package might break this. That's why I do not want to release another version.

> The package is a proprietary code unless published with the full license text. 

There is a license in this repo. Otherwise, the package and this are identical. If you aren't comfortable using the npm package, feel free to add a resolution to your package.json overriding this module with its GitHub repo.
